### ISSUE TITLE
Is possible to triangulate polygon with holes ?

### ISSUE THREAD

**Issue by vitalfadeev** [aferust/earcut-d#2]
Is possible to triangulate polygon with holes ?
( attached image )

![polygon-b](https://user-images.githubusercontent.com/24979554/128797399-159b15db-9bb8-4a50-a011-f6872f7c8b57.png)

_This is the 'B' letter, for using in text rendering via OpenGL._

**Comment by aferust** [comment]
It looks like it does. I only ported the original implementation, and don't have in-depth information. I don't have a boilerplate code to visually test it right now. maybe you can do it?
```d
import earcutd;
import dvector;

import std.typecons: tuple, Tuple;
import core.stdc.stdio;

alias Point = Tuple!(int, int);

extern (C) int main(){

    Earcut!(size_t, Dvector!(Dvector!(Point))) earcut;
    Dvector!(Dvector!(Point)) polygon;
    Dvector!(Point) p1, holes;

    scope(exit){
        earcut.indices.free;
        p1.free;
        polygon.free;
        holes.free;
    }

    Point[4] pp = [tuple(0,0), tuple(0,200), tuple(400,200), tuple(400,0)];
    p1.insert(pp[], 0);

    Point[8] hh = [tuple(50,50), tuple(50,150), tuple(150,150), tuple(150,50),
                   tuple(250,50), tuple(250,150), tuple(300,150), tuple(300,50)];
    holes.insert(hh[], 0);

    polygon.pushBack(p1);
    polygon.pushBack(holes);

    earcut.run(polygon);

    foreach(ref elem; earcut.indices)
        printf("%d\n", elem);
    
    return 0;
}
```

**Comment by vitalfadeev** [comment]
I see.
I will testing.
Thank you!

**Comment by vitalfadeev** [comment]
aferust , thank you. 
Yes, contour, then holes:

```
    Point[] pp = [...];
    Point[] hh = [...];
    
    polygon.pushBack( pp );
    polygon.pushBack( hh );    
```    

It worked !

There is triangulated B, outside contour only:

![b-without-holes](https://user-images.githubusercontent.com/24979554/129128965-7cecba0c-c1bd-4766-b0da-85f56c5600a4.png)

There is triangulated B, with holes:

![b-with-holes](https://user-images.githubusercontent.com/24979554/129129039-aab56d1b-8a11-4cec-8606-116dabda752d.png)

**Comment by vitalfadeev** [comment]
And more:

![Screenshot from 2021-08-12 09-35-12](https://user-images.githubusercontent.com/24979554/129129875-79c0e3b5-0a2c-4542-a652-1c6c434d4dd4.png)
![Screenshot from 2021-08-12 09-34-48](https://user-images.githubusercontent.com/24979554/129129877-8b029e5f-bba2-4776-b43e-ae443b3d7496.png)
![Screenshot from 2021-08-12 09-34-20](https://user-images.githubusercontent.com/24979554/129129878-8bf6cb50-673b-4de0-bb08-d1d278c6b52c.png)
![Screenshot from 2021-08-12 09-34-07](https://user-images.githubusercontent.com/24979554/129129879-56a53467-7850-4c21-8a6a-11a22c0c5354.png)

![Screenshot from 2021-08-12 09-41-45](https://user-images.githubusercontent.com/24979554/129130290-8d4de3f2-0da5-4b3b-bc6e-8f9f316ae19a.png)
![Screenshot from 2021-08-12 09-41-36](https://user-images.githubusercontent.com/24979554/129130296-5d78dc4b-53fd-4055-9528-1a50aa7ee480.png)
![Screenshot from 2021-08-12 09-41-01](https://user-images.githubusercontent.com/24979554/129130300-9a3a3273-bcb9-458a-9a9e-276cab3ffa40.png)
![Screenshot from 2021-08-12 09-40-22](https://user-images.githubusercontent.com/24979554/129130301-c7ed19af-799a-49b9-97ef-b9fa7617bf82.png)
![Screenshot from 2021-08-12 09-40-15](https://user-images.githubusercontent.com/24979554/129130303-d4c8fc9c-13f9-4d0f-a445-0e2c30450ed1.png)
![Screenshot from 2021-08-12 09-40-07](https://user-images.githubusercontent.com/24979554/129130304-fe5396f2-0599-406c-afb3-68fbf3cf9f55.png)
![Screenshot from 2021-08-12 09-39-59](https://user-images.githubusercontent.com/24979554/129130307-b4aad654-49c0-41f5-aafb-21e34d3ce6f7.png)
![Screenshot from 2021-08-12 09-39-25](https://user-images.githubusercontent.com/24979554/129130310-15e08a61-be5e-4e7d-b87f-09371c3f8050.png)
![Screenshot from 2021-08-12 09-38-38](https://user-images.githubusercontent.com/24979554/129130312-6f7d5eae-4789-4adf-924d-321ccf6b7b18.png)
![Screenshot from 2021-08-12 09-38-22](https://user-images.githubusercontent.com/24979554/129130313-3f8a5ef4-d2f8-4990-97b0-3d34bd20f079.png)
![Screenshot from 2021-08-12 09-38-12](https://user-images.githubusercontent.com/24979554/129130314-162a1300-1335-4e8c-8789-1980c8583c7c.png)
![Screenshot from 2021-08-12 09-38-06](https://user-images.githubusercontent.com/24979554/129130318-50c4627f-4bd0-4dd3-a11d-219dfde3c8e8.png)
![Screenshot from 2021-08-12 09-37-57](https://user-images.githubusercontent.com/24979554/129130320-571509c4-88e0-4358-8fc8-3a8766bd4231.png)

**Comment by aferust** [comment]
Hey, this is great, thank you for sharing it. If I find some time, maybe I include a very basic example using one of sdl-opengl, glfw-opengl, or arsd:simpledisplay-opengl.
